"""Generate the stride-8 powers table for H_PEDERSEN.

Produces circuits/ec/powers/bn254_hp_pows.circom, the precomputed table the
ScalarMulHP gadget reads, in the same shape as the existing H table:

    powers[i][j] = j * 2^(i*8) * H_PEDERSEN,  32 windows x 256 entries

H_PEDERSEN is hashed to the curve rather than multiplied out of G, so nobody
knows its discrete log -- which is what B1's composition of a sigma with a
membership proof requires of the point it commits against.  See
alberta_buck/wallet/nums.py for why that matters and where it does not.

Run:  PYTHONPATH=.:core/python python scripts/snark/gen_bn254_hp_pows.py \
        > circuits/ec/powers/bn254_hp_pows.circom
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from alberta_buck.wallet.bn254 import ORDER, mul, point_to_words
from alberta_buck.wallet.nums import H_PEDERSEN

STRIDE = 8
PARTS = 256 // STRIDE          # 32


def to_limbs(val, n=4, bits=64):
    mask = (1 << bits) - 1
    return [(val >> (i * bits)) & mask for i in range(n)]


def main():
    out = [
        "pragma circom 2.1.6;",
        "",
        "// BN254 H_PEDERSEN-powers: stride-8 precomputed table.",
        "// Auto-generated by scripts/snark/gen_bn254_hp_pows.py -- DO NOT EDIT.",
        "//",
        "// H_PEDERSEN is hashed to the curve, not multiplied out of G, so its",
        "// discrete log is unknown.  That is what makes B1's P_dep a real",
        "// commitment: the sigma's opening and the membership proof's opening",
        "// must agree, and with a known log they need not.",
        f"// parts={PARTS}, STRIDE={STRIDE}",
        "",
        "function getHPPowStride8Table(n, k) {",
        "    assert(n == 64 && k == 4);",
        f"    var powers[{PARTS}][256][2][4];",
        "",
    ]
    for win in range(PARTS):
        base = pow(2, win * STRIDE, ORDER)
        for j in range(256):
            if j == 0:
                xl, yl = [0, 0, 0, 0], [0, 0, 0, 0]
            else:
                x, y = point_to_words(mul(H_PEDERSEN, (j * base) % ORDER))
                xl, yl = to_limbs(x), to_limbs(y)
            for i in range(4):
                out.append(f"    powers[{win}][{j}][0][{i}] = {xl[i]};")
            for i in range(4):
                out.append(f"    powers[{win}][{j}][1][{i}] = {yl[i]};")
        out.append("")
    out += ["    return powers;", "}", ""]
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
