"""Generate BN254 G-powers stride-8 table for circom-lib EC scalar multiplication.

Produces circuits/ec/powers/bn254_g_pows.circom.

Pattern: powers[parts][256][2][4] — 32 windows × 256 precomputed points.
powers[i][j] = j * 2^(i*STRIDE) * G
"""

import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from alberta_buck.wallet.bn254 import G1, mul, point_to_words, ORDER

STRIDE = 8
PARTS = 256 // STRIDE  # 32


def to_limbs(val, n=4, bits=64):
    mask = (1 << bits) - 1
    return [(val >> (i * bits)) & mask for i in range(n)]


def main():
    out = []
    out.append('// BN254 G-powers: stride-8 precomputed table for G = (1, 2)')
    out.append('// Auto-generated by scripts/snark/gen_bn254_g_pows.py — DO NOT EDIT')
    out.append(f'// parts={PARTS}, STRIDE={STRIDE}')
    out.append('')
    out.append('function getGPowStride8TableBN254(CHUNK_SIZE, CHUNK_NUMBER) {')
    out.append('    assert(CHUNK_SIZE == 64 && CHUNK_NUMBER == 4);')
    out.append(f'    var ret[{PARTS}][256][2][4];')

    for win in range(PARTS):
        base_exp = win * STRIDE
        for j in range(256):
            if j == 0:
                xl, yl = [0, 0, 0, 0], [0, 0, 0, 0]
            else:
                scalar = (j * pow(2, base_exp, ORDER)) % ORDER
                pt = mul(G1, scalar)
                x, y = point_to_words(pt)
                xl, yl = to_limbs(x), to_limbs(y)
            out.append(
                f'    ret[{win}][{j}][0][0] = {xl[0]}; '
                f'ret[{win}][{j}][0][1] = {xl[1]}; '
                f'ret[{win}][{j}][0][2] = {xl[2]}; '
                f'ret[{win}][{j}][0][3] = {xl[3]}; '
                f'ret[{win}][{j}][1][0] = {yl[0]}; '
                f'ret[{win}][{j}][1][1] = {yl[1]}; '
                f'ret[{win}][{j}][1][2] = {yl[2]}; '
                f'ret[{win}][{j}][1][3] = {yl[3]};'
            )

    out.append('    return ret;')
    out.append('}')
    out.append('')
    print('\n'.join(out))


if __name__ == '__main__':
    main()
