#!/usr/bin/env node
/**
 * Emit the EVM bytecode of a 2-input Poseidon (Poseidon-T3) contract over
 * BN254's scalar field, using circomlibjs's `poseidonContract.createCode(2)`.
 * The on-chain bytecode is the standard Tornado-Cash-style Poseidon helper:
 * single function selector `poseidon(uint256[2])` returning a single uint256.
 *
 * Two artifacts are produced:
 *   - build/snark/poseidon/PoseidonT3.bytecode.hex  (pure deployment bytecode)
 *   - test/harness/PoseidonT3Bytecode.sol           (Solidity helper with the
 *                                                    bytecode as a constant
 *                                                    plus a `deploy()` that
 *                                                    CREATEs the contract)
 *
 * The unoptimized circomlibjs Poseidon (full M matrix + per-round K) is
 * mathematically identical to the circomlib *circuit* Poseidon (which uses
 * pre-folded P matrices and sparse S matrices for fewer R1CS constraints):
 * both produce the same hash for the same field-element inputs.
 *
 * Run: node scripts/snark/poseidon_t3_code.js
 */
"use strict";

const fs   = require("fs");
const path = require("path");
const cjs  = require("circomlibjs");

const ROOT  = path.resolve(__dirname, "..", "..");
const OUT_BIN = path.join(ROOT, "build", "snark", "poseidon");
const OUT_SOL = path.join(ROOT, "src", "PoseidonT3Bytecode.sol");

function main() {
    const code = cjs.poseidonContract.createCode(2);
    if (typeof code !== "string" || !code.startsWith("0x")) {
        throw new Error("poseidonContract.createCode did not return 0x... bytecode");
    }

    fs.mkdirSync(OUT_BIN, { recursive: true });
    const binPath = path.join(OUT_BIN, "PoseidonT3.bytecode.hex");
    fs.writeFileSync(binPath, code + "\n");
    console.log(`wrote ${binPath} (${(code.length - 2) / 2} bytes)`);

    // Solidity helper: a constant `BYTECODE` plus a `deploy()` that returns
    // the new contract address.  The test setUp deploys this once and hands
    // the address to Notes' constructor.
    const sol =
`// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity ^0.8.20;

// AUTO-GENERATED by scripts/snark/poseidon_t3_code.js -- do not hand-edit.
//
// EVM bytecode for the circomlibjs Poseidon-T3 (2-input, BN254 scalar field)
// helper contract.  Single function selector: poseidon(uint256[2]) returns
// (uint256).  Mathematically identical to the circomlib circuit Poseidon(2);
// the unoptimized representation here just trades pre-folded matrices for
// raw M/K constants -- same hash for the same inputs.
library PoseidonT3Bytecode {
    bytes internal constant BYTECODE = hex"${code.slice(2)}";

    function deploy() internal returns (address addr) {
        bytes memory code_ = BYTECODE;
        assembly {
            addr := create(0, add(code_, 0x20), mload(code_))
        }
        require(addr != address(0), "PoseidonT3: deploy failed");
    }
}
`;
    fs.mkdirSync(path.dirname(OUT_SOL), { recursive: true });
    fs.writeFileSync(OUT_SOL, sol);
    console.log(`wrote ${OUT_SOL}`);
}

main();
