#!/usr/bin/env node
/**
 * Emit the EVM bytecode of an N-input Poseidon contract (Poseidon-T{N+1}) over
 * BN254's scalar field, using circomlibjs's `poseidonContract.createCode(N)`.
 * The on-chain bytecode is the standard Tornado-Cash-style Poseidon helper:
 * single function selector `poseidon(uint256[N])` returning a single uint256.
 *
 * Two artifacts are produced, for T = N + 1:
 *   - build/snark/poseidon/PoseidonT<T>.bytecode.hex  (pure deployment bytecode)
 *   - src/PoseidonT<T>Bytecode.sol                    (Solidity helper with the
 *                                                      bytecode as a constant
 *                                                      plus a `deploy()` that
 *                                                      CREATEs the contract)
 *
 * T3 hashes Merkle nodes; T4 hashes the tagged identity leaf
 * Poseidon(TAG, M.x, M.y), which a public membership proof opens on chain.
 *
 * The unoptimized circomlibjs Poseidon (full M matrix + per-round K) is
 * mathematically identical to the circomlib *circuit* Poseidon (which uses
 * pre-folded P matrices and sparse S matrices for fewer R1CS constraints):
 * both produce the same hash for the same field-element inputs.
 *
 * Run: node scripts/snark/poseidon_code.js 2     # PoseidonT3
 *      node scripts/snark/poseidon_code.js 3     # PoseidonT4
 */
"use strict";

const fs   = require("fs");
const path = require("path");
const cjs  = require("circomlibjs");

const ROOT  = path.resolve(__dirname, "..", "..");
const OUT_BIN = path.join(ROOT, "build", "snark", "poseidon");

function main() {
    const N = parseInt(process.argv[2] || "2", 10);
    if (!(N >= 1 && N <= 6)) throw new Error("inputs must be 1..6");
    const T = N + 1;
    const OUT_SOL = path.join(ROOT, "src", `PoseidonT${T}Bytecode.sol`);
    const code = cjs.poseidonContract.createCode(N);
    if (typeof code !== "string" || !code.startsWith("0x")) {
        throw new Error("poseidonContract.createCode did not return 0x... bytecode");
    }

    fs.mkdirSync(OUT_BIN, { recursive: true });
    const binPath = path.join(OUT_BIN, `PoseidonT${T}.bytecode.hex`);
    fs.writeFileSync(binPath, code + "\n");
    console.log(`wrote ${binPath} (${(code.length - 2) / 2} bytes)`);

    // Solidity helper: a constant `BYTECODE` plus a `deploy()` that returns
    // the new contract address.  A test setUp deploys it once and hands the
    // address to the contract that hashes with it.
    const sol =
`// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity ^0.8.20;

// AUTO-GENERATED by scripts/snark/poseidon_code.js -- do not hand-edit.
//
// EVM bytecode for the circomlibjs Poseidon-T${T} (${N}-input, BN254 scalar field)
// helper contract.  Single function selector: poseidon(uint256[${N}]) returns
// (uint256).  Mathematically identical to the circomlib circuit Poseidon(${N});
// the unoptimized representation here just trades pre-folded matrices for
// raw M/K constants -- same hash for the same inputs.
library PoseidonT${T}Bytecode {
    bytes internal constant BYTECODE = hex"${code.slice(2)}";

    function deploy() internal returns (address addr) {
        bytes memory code_ = BYTECODE;
        assembly {
            addr := create(0, add(code_, 0x20), mload(code_))
        }
        require(addr != address(0), "PoseidonT${T}: deploy failed");
    }
}
`;
    fs.mkdirSync(path.dirname(OUT_SOL), { recursive: true });
    fs.writeFileSync(OUT_SOL, sol);
    console.log(`wrote ${OUT_SOL}`);
}

main();
