// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";

import {BN254}                 from "../src/BN254.sol";
import {IdentityRegistry}      from "../src/IdentityRegistry.sol";
import {Buck}                  from "../src/Buck.sol";
import {BuckCredit}            from "../src/BuckCredit.sol";
import {BuckKControllerStatic} from "../src/BuckKControllerStatic.sol";
import {Notes}                 from "../src/Notes.sol";
import {MintGroth16Verifier}   from "../src/MintGroth16Verifier.sol";
import {MintVerifierAdapter}   from "../src/MintVerifierAdapter.sol";
import {PoseidonT3Bytecode}    from "../src/PoseidonT3Bytecode.sol";

/// @title MintVerifier.t.sol — end-to-end Groth16-verified mint.
/// @notice Builds the full Buck + Identity + Notes stack with a *real* mint
///         verifier, loads a proof fixture generated by scripts/snark/prove_mint.js,
///         and exercises both the happy path and the two tamper paths that
///         prove the verifier is load-bearing.
contract MintVerifierTest is Test {

    Buck                  internal buck;
    BuckCredit            internal credit;
    BuckKControllerStatic internal kCtrl;
    IdentityRegistry      internal reg;
    Notes                 internal notes;
    MintGroth16Verifier   internal g16;
    MintVerifierAdapter   internal adapter;

    address internal constant GOV    = address(0xA0);
    address internal constant ISSUER = address(0x1551E1);
    address internal constant POOL   = address(0xBA51C);

    address internal alice;
    address internal bob;

    // Fixture contents (loaded once in setUp).
    uint256   internal fxTotalFace;
    uint256[] internal fxCommitments;
    bytes     internal fxProofBytes;

    function setUp() public {
        vm.chainId(1);

        string memory ij = vm.readFile("test/vectors/identity.json");
        reg = new IdentityRegistry(GOV);
        _trustIssuer(ij);
        alice = address(uint160(vm.parseJsonUint(ij, ".alice.registrant")));
        bob   = address(uint160(vm.parseJsonUint(ij, ".bob.registrant")));
        _registerFrom(ij, "alice", alice);
        _registerFrom(ij, "bob",   bob);

        credit = new BuckCredit();
        kCtrl  = new BuckKControllerStatic(1e18, GOV);
        buck   = new Buck(address(credit), address(kCtrl), address(reg), POOL);

        g16     = new MintGroth16Verifier();
        adapter = new MintVerifierAdapter(address(g16));
        address poseidon = PoseidonT3Bytecode.deploy();
        notes   = new Notes(address(buck), address(adapter), poseidon, GOV);

        vm.prank(GOV);
        reg.setSystemPublic(address(notes), true);

        _grantCredit(alice, 1000e18);
        vm.prank(alice);
        buck.mint(500e18);
        _approveNotes(alice, 500e18);

        // Load the prover's fixture.
        string memory fx = vm.readFile("build/snark/mint/fixtures/basic.json");
        fxTotalFace = vm.parseJsonUint(fx, ".public.totalFace");
        fxCommitments = new uint256[](2);
        fxCommitments[0] = vm.parseJsonUint(fx, ".public.cm[0]");
        fxCommitments[1] = vm.parseJsonUint(fx, ".public.cm[1]");
        fxProofBytes = vm.parseJsonBytes(fx, ".proofBytes");
    }

    // ---- Identity JSON loaders (mirrors Buck.t.sol / Notes.t.sol) ---------

    function _u(string memory j, string memory k) internal pure returns (uint256) {
        return vm.parseJsonUint(j, k);
    }

    function _g1(string memory j, string memory k) internal pure returns (BN254.G1Point memory) {
        return BN254.G1Point(
            _u(j, string.concat(k, ".x")),
            _u(j, string.concat(k, ".y"))
        );
    }

    function _ct(string memory j, string memory k)
        internal pure returns (IdentityRegistry.ElGamalCT memory c)
    {
        c.R = _g1(j, string.concat(k, ".R"));
        c.C = _g1(j, string.concat(k, ".C"));
    }

    function _trustIssuer(string memory j) internal {
        IdentityRegistry.PSPubKey memory ipk;
        ipk.X.X[0] = _u(j, ".issuer.pk_X.x[0]");
        ipk.X.X[1] = _u(j, ".issuer.pk_X.x[1]");
        ipk.X.Y[0] = _u(j, ".issuer.pk_X.y[0]");
        ipk.X.Y[1] = _u(j, ".issuer.pk_X.y[1]");
        ipk.Y.X[0] = _u(j, ".issuer.pk_Y.x[0]");
        ipk.Y.X[1] = _u(j, ".issuer.pk_Y.x[1]");
        ipk.Y.Y[0] = _u(j, ".issuer.pk_Y.y[0]");
        ipk.Y.Y[1] = _u(j, ".issuer.pk_Y.y[1]");
        vm.prank(GOV);
        reg.trustIssuer(ISSUER, ipk);
    }

    function _registerFrom(string memory j, string memory who, address acct) internal {
        BN254.G1Point memory pk = _g1(j, string.concat(".", who, ".elgamal_kp.pk"));
        IdentityRegistry.ElGamalCT memory E = _ct(j, string.concat(".", who, ".ciphertext"));
        IdentityRegistry.PSSig memory sigma;
        sigma.sigma_1 = _g1(j, string.concat(".", who, ".ps_sig_rerand.sigma_1"));
        sigma.sigma_2 = _g1(j, string.concat(".", who, ".ps_sig_rerand.sigma_2"));
        IdentityRegistry.RegistrationProof memory p;
        string memory base = string.concat(".", who, ".registration_proof");
        p.e    = _u(j, string.concat(base, ".e"));
        p.s_m  = _u(j, string.concat(base, ".s_m"));
        p.s_r  = _u(j, string.concat(base, ".s_r"));
        p.A_ps = _g1(j, string.concat(base, ".A_ps"));
        p.T_C  = _g1(j, string.concat(base, ".T_C"));
        p.T_R  = _g1(j, string.concat(base, ".T_R"));
        vm.prank(acct);
        reg.register(ISSUER, pk, E, sigma, p);
    }

    function _grantCredit(address client, uint256 faceValue) internal {
        uint256 tokenId = credit.createCredit(
            client, 0, faceValue, faceValue,
            BuckCredit.DepreciationType.NONE, 0, 0, 0
        );
        vm.prank(client);
        credit.activate(tokenId, faceValue);
    }

    function _approveNotes(address from, uint256 amount) internal {
        IdentityRegistry.ElGamalCT memory junk;
        IdentityRegistry.CPProof memory junkPi;
        vm.prank(from);
        buck.approve(address(notes), amount, junk, junkPi);
    }

    // ---- tests -------------------------------------------------------------

    function test_fixture_loaded() public view {
        assertEq(fxTotalFace, 125e18, "fixture totalFace");
        assertEq(fxCommitments.length, 2);
        assertGt(fxCommitments[0], 0);
        assertGt(fxCommitments[1], 0);
        // abi.encode(uint256[2], uint256[2][2], uint256[2]) is fully static:
        // 2 + 4 + 2 = 8 slots -> 8 * 32 = 256 bytes (no length/offset overhead).
        assertEq(fxProofBytes.length, 256);
    }

    function test_mint_acceptedByGroth16Verifier() public {
        uint256 aliceBefore = buck.balanceOf(alice);
        uint256 poolBefore  = buck.balanceOf(address(notes));

        vm.prank(alice);
        notes.mint(fxProofBytes, fxCommitments, fxTotalFace);

        assertEq(buck.balanceOf(alice), aliceBefore - fxTotalFace);
        assertEq(buck.balanceOf(address(notes)), poolBefore + fxTotalFace);
        assertEq(notes.noteFaceSum(), fxTotalFace);
        assertEq(notes.commitmentCount(), 2);
        assertEq(notes.commitments(0), fxCommitments[0]);
        assertEq(notes.commitments(1), fxCommitments[1]);
    }

    function test_mint_rejectedOnTamperedTotalFace() public {
        vm.prank(alice);
        vm.expectRevert(bytes("Notes: bad mint proof"));
        notes.mint(fxProofBytes, fxCommitments, fxTotalFace + 1);
    }

    function test_mint_rejectedOnTamperedCommitment() public {
        uint256[] memory bad = new uint256[](2);
        bad[0] = fxCommitments[0] ^ 1;
        bad[1] = fxCommitments[1];
        vm.prank(alice);
        vm.expectRevert(bytes("Notes: bad mint proof"));
        notes.mint(fxProofBytes, bad, fxTotalFace);
    }

    function test_mint_rejectedOnWrongBatchSize() public {
        uint256[] memory one = new uint256[](1);
        one[0] = fxCommitments[0];
        vm.prank(alice);
        vm.expectRevert(bytes("Notes: bad mint proof"));
        notes.mint(fxProofBytes, one, fxTotalFace);
    }

    function test_mint_rejectedOnMalformedProofBytes() public {
        vm.prank(alice);
        vm.expectRevert(); // abi.decode will revert on wrong-length bytes
        notes.mint(hex"dead", fxCommitments, fxTotalFace);
    }

    function test_adapter_constructor_rejectsZero() public {
        vm.expectRevert(bytes("verifier=0"));
        new MintVerifierAdapter(address(0));
    }
}
