// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";

import {BN254}                       from "../src/BN254.sol";
import {IdentityRegistry}            from "../src/IdentityRegistry.sol";
import {Buck}                        from "../src/Buck.sol";
import {BuckCredit}                  from "../src/BuckCredit.sol";
import {BuckKControllerStatic}       from "../src/BuckKControllerStatic.sol";
import {Notes}                       from "../src/Notes.sol";
import {MintBatchN16Groth16Verifier} from "../src/MintBatchN16Groth16Verifier.sol";
import {MintVerifierAdapter}         from "../src/MintVerifierAdapter.sol";
import {StubSpendVerifier}           from "../src/StubSpendVerifier.sol";

/// @title MintVerifier.t.sol -- end-to-end Groth16-verified batch mint.
/// @notice Builds the full Buck + Identity + Notes stack with a *real* mint
///         verifier (N=16 mint_batch circuit), loads a proof fixture
///         generated by scripts/snark/prove_mint_batch.js, and exercises
///         the happy path plus tamper paths that prove the verifier is
///         load-bearing.
contract MintVerifierTest is Test {

    Buck                        internal buck;
    BuckCredit                  internal credit;
    BuckKControllerStatic       internal kCtrl;
    IdentityRegistry            internal reg;
    Notes                       internal notes;
    MintBatchN16Groth16Verifier internal g16;
    MintVerifierAdapter         internal adapter;

    address internal constant GOV    = address(0xA0);
    address internal constant ISSUER = address(0x1551E1);
    address internal constant POOL   = address(0xBA51C);

    address internal alice;
    address internal bob;

    // Fixture contents (loaded once in setUp).
    uint256   internal fxN;
    uint256   internal fxOldRoot;
    uint256   internal fxNewRoot;
    uint256   internal fxNextLeafIndex;
    uint256   internal fxTotalFace;
    uint256[] internal fxCommitments;
    bytes     internal fxProofBytes;

    function setUp() public {
        vm.chainId(1);

        string memory ij = vm.readFile("test/vectors/identity.json");
        reg = new IdentityRegistry(GOV);
        _trustIssuer(ij);
        alice = address(uint160(vm.parseJsonUint(ij, ".alice.registrant")));
        bob   = address(uint160(vm.parseJsonUint(ij, ".bob.registrant")));
        _registerFrom(ij, "alice", alice);
        _registerFrom(ij, "bob",   bob);

        credit = new BuckCredit();
        kCtrl  = new BuckKControllerStatic(1e18, GOV);
        buck   = new Buck(address(credit), address(kCtrl), address(reg), POOL);

        g16     = new MintBatchN16Groth16Verifier();
        adapter = new MintVerifierAdapter(GOV);
        vm.prank(GOV);
        adapter.registerVerifier(16, address(g16));

        StubSpendVerifier spendStub = new StubSpendVerifier(GOV);
        notes   = new Notes(
            address(buck), address(adapter), address(spendStub), GOV
        );

        vm.prank(GOV);
        reg.setSystemPublic(address(notes), true);

        // Generous credit + balance so Alice can mint up to N*1e18.
        _grantCredit(alice, 10000e18);
        vm.prank(alice);
        buck.mint(5000e18);
        _approveNotes(alice, 5000e18);

        // Load the prover's fixture (basic: N=16, startLeaf=0, oldRoot=empty).
        string memory fx = vm.readFile("build/snark/mint_batch_n16/fixtures/basic.json");
        fxN             = vm.parseJsonUint(fx, ".N");
        fxOldRoot       = vm.parseJsonUint(fx, ".public.oldRoot");
        fxNewRoot       = vm.parseJsonUint(fx, ".public.newRoot");
        fxNextLeafIndex = vm.parseJsonUint(fx, ".public.nextLeafIndex");
        fxTotalFace     = vm.parseJsonUint(fx, ".public.totalFace");
        fxCommitments   = new uint256[](fxN);
        for (uint256 i = 0; i < fxN; i++) {
            string memory key = string.concat(".public.cm[", vm.toString(i), "]");
            fxCommitments[i] = vm.parseJsonUint(fx, key);
        }
        fxProofBytes = vm.parseJsonBytes(fx, ".proofBytes");
    }

    // ---- Identity JSON loaders (mirrors Buck.t.sol / Notes.t.sol) ---------

    function _u(string memory j, string memory k) internal pure returns (uint256) {
        return vm.parseJsonUint(j, k);
    }

    function _g1(string memory j, string memory k) internal pure returns (BN254.G1Point memory) {
        return BN254.G1Point(
            _u(j, string.concat(k, ".x")),
            _u(j, string.concat(k, ".y"))
        );
    }

    function _ct(string memory j, string memory k)
        internal pure returns (IdentityRegistry.ElGamalCT memory c)
    {
        c.R = _g1(j, string.concat(k, ".R"));
        c.C = _g1(j, string.concat(k, ".C"));
    }

    function _trustIssuer(string memory j) internal {
        IdentityRegistry.PSPubKey memory ipk;
        ipk.X.X[0] = _u(j, ".issuer.pk_X.x[0]");
        ipk.X.X[1] = _u(j, ".issuer.pk_X.x[1]");
        ipk.X.Y[0] = _u(j, ".issuer.pk_X.y[0]");
        ipk.X.Y[1] = _u(j, ".issuer.pk_X.y[1]");
        ipk.Y.X[0] = _u(j, ".issuer.pk_Y.x[0]");
        ipk.Y.X[1] = _u(j, ".issuer.pk_Y.x[1]");
        ipk.Y.Y[0] = _u(j, ".issuer.pk_Y.y[0]");
        ipk.Y.Y[1] = _u(j, ".issuer.pk_Y.y[1]");
        vm.prank(GOV);
        reg.trustIssuer(ISSUER, ipk);
    }

    function _registerFrom(string memory j, string memory who, address acct) internal {
        BN254.G1Point memory pk = _g1(j, string.concat(".", who, ".elgamal_kp.pk"));
        IdentityRegistry.ElGamalCT memory E = _ct(j, string.concat(".", who, ".ciphertext"));
        IdentityRegistry.PSSig memory sigma;
        sigma.sigma_1 = _g1(j, string.concat(".", who, ".ps_sig_rerand.sigma_1"));
        sigma.sigma_2 = _g1(j, string.concat(".", who, ".ps_sig_rerand.sigma_2"));
        IdentityRegistry.RegistrationProof memory p;
        string memory base = string.concat(".", who, ".registration_proof");
        p.e    = _u(j, string.concat(base, ".e"));
        p.s_m  = _u(j, string.concat(base, ".s_m"));
        p.s_r  = _u(j, string.concat(base, ".s_r"));
        p.A_ps = _g1(j, string.concat(base, ".A_ps"));
        p.T_C  = _g1(j, string.concat(base, ".T_C"));
        p.T_R  = _g1(j, string.concat(base, ".T_R"));
        vm.prank(acct);
        reg.register(ISSUER, pk, E, sigma, p);
    }

    function _grantCredit(address client, uint256 faceValue) internal {
        uint256 tokenId = credit.createCredit(
            client, 0, faceValue, faceValue,
            BuckCredit.DepreciationType.NONE, 0, 0, 0
        );
        vm.prank(client);
        credit.activate(tokenId, faceValue);
    }

    function _approveNotes(address from, uint256 amount) internal {
        IdentityRegistry.ElGamalCT memory junk;
        IdentityRegistry.CPProof memory junkPi;
        vm.prank(from);
        buck.approve(address(notes), amount, junk, junkPi);
    }

    function _mint(
        bytes memory proof,
        uint256 oldRoot,
        uint256 newRoot,
        uint256 nextLeafIndex,
        uint256 totalFace,
        uint256[] memory cms
    ) internal {
        vm.prank(alice);
        notes.mint(proof, oldRoot, newRoot, uint32(nextLeafIndex), totalFace, cms);
    }

    // ---- tests -------------------------------------------------------------

    function test_fixture_loaded() public view {
        assertEq(fxN, 16,             "N=16");
        assertEq(fxOldRoot, notes.EMPTY_ROOT(), "fixture oldRoot is empty tree");
        assertEq(fxNextLeafIndex, 0);
        assertEq(fxCommitments.length, 16);
        assertGt(fxTotalFace, 0,      "totalFace should be sum of v_i");
        assertEq(fxProofBytes.length, 256);
    }

    function test_mint_acceptedByGroth16Verifier() public {
        uint256 aliceBefore = buck.balanceOf(alice);
        uint256 poolBefore  = buck.balanceOf(address(notes));

        _mint(fxProofBytes, fxOldRoot, fxNewRoot, fxNextLeafIndex, fxTotalFace, fxCommitments);

        assertEq(buck.balanceOf(alice),          aliceBefore - fxTotalFace);
        assertEq(buck.balanceOf(address(notes)), poolBefore + fxTotalFace);
        assertEq(notes.noteFaceSum(),  fxTotalFace);
        assertEq(notes.nextLeafIndex(), 16);
        assertEq(notes.noteRoot(),     fxNewRoot);
    }

    function test_mint_rejectedOnTamperedTotalFace() public {
        vm.prank(alice);
        vm.expectRevert(bytes("Notes: bad mint proof"));
        notes.mint(
            fxProofBytes, fxOldRoot, fxNewRoot, uint32(fxNextLeafIndex),
            fxTotalFace + 1, fxCommitments
        );
    }

    function test_mint_rejectedOnTamperedNewRoot() public {
        uint256 bogusRoot = uint256(keccak256("bogus")) % notes.FIELD_R();
        vm.prank(alice);
        vm.expectRevert(bytes("Notes: bad mint proof"));
        notes.mint(
            fxProofBytes, fxOldRoot, bogusRoot, uint32(fxNextLeafIndex),
            fxTotalFace, fxCommitments
        );
    }

    function test_mint_rejectedOnTamperedCommitment() public {
        uint256[] memory bad = new uint256[](16);
        for (uint256 i = 0; i < 16; i++) bad[i] = fxCommitments[i];
        bad[0] = fxCommitments[0] ^ 1;
        vm.prank(alice);
        vm.expectRevert(bytes("Notes: bad mint proof"));
        notes.mint(
            fxProofBytes, fxOldRoot, fxNewRoot, uint32(fxNextLeafIndex),
            fxTotalFace, bad
        );
    }

    function test_mint_rejectedOnWrongBatchSize() public {
        // The adapter has no verifier registered for N=15 -> returns false.
        uint256[] memory shorter = new uint256[](15);
        for (uint256 i = 0; i < 15; i++) shorter[i] = fxCommitments[i];
        vm.prank(alice);
        vm.expectRevert(bytes("Notes: bad mint proof"));
        notes.mint(
            fxProofBytes, fxOldRoot, fxNewRoot, uint32(fxNextLeafIndex),
            fxTotalFace, shorter
        );
    }

    function test_mint_rejectedOnTamperedOldRoot() public {
        // oldRoot != live root -> stale-state guard catches it before the
        // verifier is even called.
        uint256 bogusOld = uint256(keccak256("notlive")) % notes.FIELD_R();
        vm.prank(alice);
        vm.expectRevert(bytes("Notes: stale oldRoot"));
        notes.mint(
            fxProofBytes, bogusOld, fxNewRoot, uint32(fxNextLeafIndex),
            fxTotalFace, fxCommitments
        );
    }

    function test_mint_rejectedOnTamperedNextLeafIndex() public {
        // nextLeafIndex != live -> stale-state guard.
        vm.prank(alice);
        vm.expectRevert(bytes("Notes: stale nextLeafIndex"));
        notes.mint(
            fxProofBytes, fxOldRoot, fxNewRoot, uint32(fxNextLeafIndex + 1),
            fxTotalFace, fxCommitments
        );
    }

    function test_mint_rejectedOnMalformedProofBytes() public {
        // Adapter rejects proof.length != 256 by returning false; Notes
        // surfaces that as the verifier-rejection error.
        vm.prank(alice);
        vm.expectRevert(bytes("Notes: bad mint proof"));
        notes.mint(
            hex"dead", fxOldRoot, fxNewRoot, uint32(fxNextLeafIndex),
            fxTotalFace, fxCommitments
        );
    }

    function test_adapter_constructor_rejectsZero() public {
        vm.expectRevert(bytes("governance=0"));
        new MintVerifierAdapter(address(0));
    }

    function test_adapter_registerVerifier_governance() public {
        MintVerifierAdapter a = new MintVerifierAdapter(GOV);
        vm.expectRevert(bytes("not governance"));
        a.registerVerifier(16, address(g16));
        vm.prank(GOV);
        vm.expectRevert(bytes("n=0"));
        a.registerVerifier(0, address(g16));
        vm.prank(GOV);
        vm.expectRevert(bytes("verifier=0"));
        a.registerVerifier(16, address(0));
        vm.prank(GOV);
        a.registerVerifier(16, address(g16));
        assertEq(a.verifiers(16), address(g16));
    }
}
