// Golden-vector conformance, JS side: every row of
// test/vectors/math-vectors.json (generated by test/MathVectors.t.sol
// from the REAL contract code paths) must reproduce bit-identically
// through the buck-math WASM kernel.  The Rust and Python suites assert
// the same file.  All values cross as BigInt.
//
// Build the kernel first:  make nix-core-build-wasm

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
let wasm = null;
try {
  wasm = require("../wasm/buck_math.js");
} catch {
  // not built; tests below skip
}

const VECTORS = fileURLToPath(
  new URL("../../../test/vectors/math-vectors.json", import.meta.url));
const rows = JSON.parse(readFileSync(VECTORS, "utf8"));
const skip = wasm ? false : "kernel not built (make nix-core-build-wasm)";

const B = BigInt;

test("depreciation vectors", { skip }, () => {
  let n = 0;
  for (const r of rows.filter((r) => r.s === "dep")) {
    const got = wasm.depreciate(B(r.face), Number(r.dep_type),
                                Number(r.rate_bp), B(r.floor), 0n,
                                B(r.elapsed));
    assert.equal(got, B(r.value), JSON.stringify(r));
    n += 1;
  }
  assert.ok(n >= 250);
});

test("fee vectors", { skip }, () => {
  let n = 0;
  for (const r of rows.filter((r) => r.s === "fee")) {
    const got = wasm.fee_owing(B(r.buck_seconds), B(r.raw), B(r.elapsed));
    assert.equal(got, B(r.fee), JSON.stringify(r));
    n += 1;
  }
  assert.ok(n >= 60);
});

test("carrying vectors", { skip }, () => {
  let n = 0;
  for (const r of rows.filter((r) => r.s === "carry")) {
    const got = wasm.carrying_transfer(
      B(r.from_raw), B(r.from_bs), B(r.from_elapsed),
      B(r.to_raw), B(r.to_bs), B(r.to_elapsed), B(r.value));
    assert.equal(got.from_raw, B(r.from_raw_after), JSON.stringify(r));
    assert.equal(got.from_bs, B(r.from_bs_after), JSON.stringify(r));
    assert.equal(got.to_raw, B(r.to_raw_after), JSON.stringify(r));
    assert.equal(got.to_bs, B(r.to_bs_after), JSON.stringify(r));
    n += 1;
  }
  assert.ok(n >= 8);
});

test("funding-factor vectors", { skip }, () => {
  let n = 0;
  const pid = new wasm.DirectPid(0n, 1n, 0n, 600n, 0n,
                                 10n ** 18n, 5n * 10n ** 17n, 0n);
  for (const r of rows.filter((r) => r.s === "ff")) {
    pid.last_basket_cost = B(r.basket);
    pid.last_buck_price = B(r.buck);
    assert.equal(pid.funding_factor(), B(r.factor), JSON.stringify(r));
    n += 1;
  }
  assert.ok(n >= 10);
});

test("pid vectors", { skip }, () => {
  let pid = null;
  let n = 0;
  for (const r of rows) {
    if (r.s === "pid_params") {
      pid = new wasm.DirectPid(B(r.kp), B(r.ki), B(r.kd), B(r.dt),
                               B(r.kmin), B(r.kmax), B(r.k0), B(r.t0));
      pid.dt_max = B(r.dt_max);
    } else if (r.s === "pid") {
      const k = pid.compute(B(r.t), B(r.basket));
      assert.equal(k, B(r.buck_k), JSON.stringify(r));
      assert.equal(pid.p, B(r.p), JSON.stringify(r));
      assert.equal(pid.i, B(r.i), JSON.stringify(r));
      assert.equal(pid.d, B(r.d), JSON.stringify(r));
      assert.equal(pid.last_update, B(r.last_update), JSON.stringify(r));
      assert.equal(pid.funding_factor(), B(r.ff), JSON.stringify(r));
      n += 1;
    }
  }
  assert.equal(n, 12);
});
