//! Poseidon constants codegen.
//!
//! Converts `constants/poseidon_constants.json` (the same file
//! `alberta_buck/wallet/poseidon.py` loads) into static `[u64; 4]` limb
//! arrays.  Keeping the JSON as the single source of truth -- rather than
//! committing generated Rust -- makes "same constants as the circuits and
//! the Python reference" an auditable file compare.
//!
//! The JSON itself is emitted by `constants/generate.py` from the Poseidon
//! specification's Grain LFSR; it is byte-identical to circomlib's file,
//! but derived rather than copied (`make poseidon-constants-check`, NOTICE).

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// "0x..."-hex field element -> little-endian u64 limbs.
fn limbs(hex: &str) -> [u64; 4] {
    let h = hex.strip_prefix("0x").unwrap_or(hex);
    let padded = format!("{:0>64}", h);
    let mut out = [0u64; 4];
    for (i, limb) in out.iter_mut().enumerate() {
        // limb 0 is least significant = the LAST 16 hex chars.
        let start = 64 - (i + 1) * 16;
        *limb = u64::from_str_radix(&padded[start..start + 16], 16).unwrap();
    }
    out
}

fn emit_slice(out: &mut String, values: &[serde_json::Value]) {
    out.push_str("&[");
    for v in values {
        let l = limbs(v.as_str().expect("poseidon constant must be a hex string"));
        write!(out, "[{},{},{},{}],", l[0], l[1], l[2], l[3]).unwrap();
    }
    out.push_str("],\n");
}

fn main() {
    println!("cargo:rerun-if-changed=constants/poseidon_constants.json");
    let txt = fs::read_to_string("constants/poseidon_constants.json")
        .expect("constants/poseidon_constants.json missing");
    let data: serde_json::Value = serde_json::from_str(&txt).unwrap();

    let c = data["C"].as_array().expect("C");
    let m = data["M"].as_array().expect("M");
    assert_eq!(c.len(), 16, "expected constants for t = 2..=17");
    assert_eq!(m.len(), 16);

    let mut out = String::new();
    out.push_str("// Generated by build.rs from constants/poseidon_constants.json.\n");
    out.push_str("// Index by t - 2 (state width t = arity + 1).  Limbs little-endian.\n");

    out.push_str("pub static C_ALL: [&[[u64; 4]]; 16] = [\n");
    for row in c {
        emit_slice(&mut out, row.as_array().unwrap());
    }
    out.push_str("];\n");

    out.push_str("pub static M_ALL: [&[[u64; 4]]; 16] = [\n");
    for (idx, mat) in m.iter().enumerate() {
        let t = idx + 2;
        let mat = mat.as_array().unwrap();
        assert_eq!(mat.len(), t, "M[{idx}] must be {t}x{t}");
        // Flatten row-major: element (i, j) at i*t + j.
        let flat: Vec<serde_json::Value> = mat
            .iter()
            .flat_map(|r| r.as_array().unwrap().clone())
            .collect();
        assert_eq!(flat.len(), t * t);
        emit_slice(&mut out, &flat);
    }
    out.push_str("];\n");

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("poseidon_constants.rs");
    fs::write(dest, out).unwrap();
}
