;; Batch re-execution + render of alberta-buck-notes-flow.org.
;;
;; The flow document is EXECUTABLE: its python blocks form one seeded
;; deterministic transcript (:session notesflow), so the RESULTS drawers
;; must be regenerated by running every block top to bottom -- inside a
;; venv where the alberta_buck package is importable.
;;
;; Usage (the venv-% Makefile wrapper activates the venv):
;;   make nix-venv-doc-flow
;; or manually:
;;   source <repo>.venv-*/bin/activate
;;   emacs --batch -l scripts/render-flow-doc.el

(require 'org)
(require 'ob-python)
(require 'ox-ascii)
(require 'ox-latex)

(setq org-confirm-babel-evaluate nil
      org-ascii-charset 'utf-8
      org-safe-remote-resources '("\\`https://perry\\.kundert\\.ca/")
      python-shell-completion-native-enable nil)

(find-file "alberta-buck-notes-flow.org")
(message "Executing babel transcript (one seeded python session)...")
;; Only the python blocks are executable; the document also carries
;; display-only blocks (solidity, text, example) that must be skipped.
(org-babel-map-src-blocks nil
  (when (string= lang "python")
    (org-babel-execute-src-block)))
(save-buffer)
(message "Exporting ascii + pdf...")
(org-ascii-export-to-ascii)
(org-latex-export-to-pdf)
(message "Done.")
