;; Batch re-execution + render of an EXECUTABLE org document.
;;
;; The executable documents (alberta-buck-notes-flow.org,
;; alberta-buck-paper.org, alberta-buck-receipt.org, alberta-buck-proofs.org,
;; alberta-buck-identity-example.org) carry python blocks forming one
;; deterministic transcript (:session per document), so
;; their RESULTS drawers must be regenerated by running every block top to
;; bottom -- inside a venv where the alberta_buck package is importable.
;; (alberta-buck-receipt.org additionally spawns a local anvil EVM, so the
;; forge artifacts must be built and anvil on PATH: run under nix.)
;;
;; Usage (the venv-% Makefile wrapper activates the venv):
;;   make nix-venv-doc-flow
;;   make nix-venv-doc-paper
;; or manually:
;;   source <repo>.venv-*/bin/activate
;;   emacs --batch -l scripts/render-exec-doc.el <file>.org

(require 'org)
(require 'ob-python)
(require 'ox-ascii)
(require 'ox-latex)

(setq org-confirm-babel-evaluate nil
      org-ascii-charset 'utf-8
      org-safe-remote-resources '("\\`https://perry\\.kundert\\.ca/")
      python-shell-completion-native-enable nil)

(let ((file (or (pop command-line-args-left)
                (error "usage: emacs --batch -l render-exec-doc.el FILE.org"))))
  (find-file file)
  (message "Executing babel transcript of %s (one seeded python session)..." file)
  ;; Only the python blocks are executable; the documents also carry
  ;; display-only blocks (solidity, text, example) that must be skipped.
  (org-babel-map-src-blocks nil
    (when (string= lang "python")
      (org-babel-execute-src-block)))
  (save-buffer)
  (message "Exporting ascii + pdf...")
  (org-ascii-export-to-ascii)
  (org-latex-export-to-pdf)
  (message "Done."))
