"""Economic invariants over the rebalancing-sim vectors.

The rebalancing simulation is the only place BuckBasketProRata meets a real
multi-agent economy on the EVM: ~427 agents against really-deployed contracts
for two simulated years.  Until this module existed it produced only pictures
-- `plot_rebalancing.py` is named `test_` and is collected by pytest, but it
contains no assertions and fails only on a crash or malformed JSON.  So 730
agent-days of EVM execution proved nothing automatically.

This module turns those vectors into a regression test.  Every assertion here
is a property that must hold for ANY valid run, not a number observed once:
conservation, cumulative counters that cannot go backwards, accounting
identities between counters, and the bounds the contracts themselves enforce.
Two of them are guards against bugs this suite was written after:

  * `dmExitFails == 0` -- when the demand leg's park bite was sized at 5% of a
    pool's BUCK side, it moved pool spot past the basket's own TWAP guard and
    honest depositors' redeems began reverting with `Slippage()`.  The
    contract was right and the agent was the manipulator.  Nothing failed;
    the render just quietly showed fewer exits.

  * a non-degenerate demand leg -- the agent once ran for a whole simulation
    without trading at all, because its trigger compared against the wrong
    price.  The counters read zero and the plot drew an empty series.

Vectors are generated by `make nix-sim-rebalancing{,-prorata,-traditional}`
and committed under test/vectors/.  A vector that does not exist is skipped;
a vector written by an older schema skips only the assertions whose fields it
lacks, so this module stays useful across regenerations.

An assertion suite that cannot fail is decoration, so this one was checked by
mutation: six damaged copies of a real vector, each of which is caught by the
one assertion meant to catch it.

    failing redeems (dmExitFails 0 -> 7)   -> test_no_failed_redemptions
    demand leg present but never trading   -> test_demand_leg_actually_trades
    NAV cut below outstanding principal    -> test_basket_stays_solvent
    a cumulative counter stepped backwards -> test_cumulative_counters_never_decrease
    weights driven to 0.90/0.05/0.05       -> test_pool_weights_track_the_mandate
    a pool price detached 40% from market  -> test_arbs_keep_the_pools_tracking_the_market
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
VECTORS = REPO / "test" / "vectors"

E6 = 10 ** 6
E18 = 10 ** 18

# Cumulative counters.  Each is a running total the snapshotter copies out of
# `ctr` every frame, so a decrease is an accounting bug, never economics.
CUMULATIVE = [
    "dmEntries", "dmExits", "dmExitFails", "dmTotalInvested",
    "dmRoundTrips", "dmDollarDays",
    "directTrades", "cycleTrades", "rebalanceTrades",
    "directorPokes", "directorTrades",
    "treasuryBuck",
    "dba_bought", "dba_sold", "dbb_bought", "dbb_sold",
    "dbb_parked", "dbb_harvests",
]

# The pairwise leash bound in PairsRebalanceDirector (30%, released at 25%).
# Pool value weights should sit far inside it; this catches a basket that has
# stopped tracking its mandate, not ordinary drift.
LEASH = 0.30

# BuckKController clamps buckK into [buckKMin, buckKMax]; KMAX is 0.95 in the
# deployed configuration.  Assert the containing box rather than the exact
# rail, because the rail is a governance parameter.
BUCK_K_MAX = 1.0

# The scenario's headline claim is that BUCK-unaware arbitrageurs keep the
# TOKEN/BUCK pools tracking the market.  A few percent is ordinary AMM drift;
# a break in routing shows up far larger than this.
MAX_TRACKING_ERR = 0.05


def _vectors():
    return [pytest.param(VECTORS / n, id=n[:-5]) for n in (
        "rebalancing-sim.json",
        "rebalancing-sim-prorata.json",
        "rebalancing-sim-traditional.json")]


def _load(path: Path) -> dict:
    if not path.exists():
        pytest.skip(f"{path.name} not generated; run make nix-sim-rebalancing")
    d = json.loads(path.read_text())
    if not d.get("frames"):
        pytest.skip(f"{path.name} has no frames")
    return d


def _series(frames, key):
    """Cumulative series, or None when this vector predates the field."""
    if not any(key in f for f in frames):
        return None
    return [f.get(key, 0) for f in frames]


@pytest.mark.parametrize("path", _vectors())
def test_frames_are_well_formed(path):
    fr = _load(path)["frames"]
    days = [f["day"] for f in fr]
    assert days == sorted(set(days)), "days must be strictly increasing"
    for key in ("basketNav", "dmOutstanding", "supply", "buckK", "basketVal"):
        assert all(key in f for f in fr), f"every frame needs {key}"


@pytest.mark.parametrize("path", _vectors())
def test_basket_stays_solvent(path):
    """NAV must cover the principal the basket has minted against deposits.

    `dmOutstanding` is the sum of buckPrincipal over live deposits -- what the
    basket owes if everyone redeems.  `basketNav` is the BUCK value of all LP
    it holds.  NAV below outstanding is the underwater case the contract
    reverts on (`test_redeem_underwater_reverts`), and it must not arise from
    ordinary agent traffic.
    """
    fr = _load(path)["frames"]
    worst, worst_day = None, None
    for f in fr:
        out = f["dmOutstanding"]
        if out <= 0:
            continue
        ratio = f["basketNav"] / out
        if worst is None or ratio < worst:
            worst, worst_day = ratio, f["day"]
    if worst is None:
        pytest.skip("no outstanding principal in this run")
    assert worst >= 1.0, (
        f"basket underwater on day {worst_day}: "
        f"NAV/outstanding = {worst:.3f}")


@pytest.mark.parametrize("path", _vectors())
def test_supply_covers_basket_principal(path):
    """Every BUCK minted against a deposit is BUCK in circulation."""
    fr = _load(path)["frames"]
    bad = [(f["day"], f["supply"], f["dmOutstanding"])
           for f in fr if f["supply"] < f["dmOutstanding"]]
    assert not bad, f"supply below basket principal on {len(bad)} frames: {bad[:3]}"


@pytest.mark.parametrize("path", _vectors())
def test_cumulative_counters_never_decrease(path):
    """A running total that goes backwards is a snapshot bug, not economics."""
    fr = _load(path)["frames"]
    checked = 0
    for key in CUMULATIVE:
        v = _series(fr, key)
        if v is None:
            continue
        checked += 1
        drops = [(fr[i + 1]["day"], v[i], v[i + 1])
                 for i in range(len(v) - 1) if v[i + 1] < v[i]]
        assert not drops, f"{key} decreased at {drops[:3]}"
    assert checked >= 5, "vector carries too few counters to be meaningful"


@pytest.mark.parametrize("path", _vectors())
def test_deposit_accounting_identities(path):
    """Exits cannot exceed entries; round-trips are booked only on exits."""
    last = _load(path)["frames"][-1]
    entries, exits = last.get("dmEntries", 0), last.get("dmExits", 0)
    assert exits <= entries, f"{exits} exits against {entries} entries"
    rt = last.get("dmRoundTrips")
    if rt is not None:
        assert rt <= exits, (
            f"{rt} round-trips booked against {exits} exits -- a round-trip is "
            "recorded only on a successful redeem")
        if rt > 0:
            assert last.get("dmDollarDays", 0) > 0, (
                "round-trips booked with no capital-time behind them; the "
                "APR they feed would divide by zero")


@pytest.mark.parametrize("path", _vectors())
def test_no_failed_redemptions(path):
    """A depositor who wants out must get out.

    This is the guard that would have caught the demand leg pushing pool spot
    past the basket's TWAP guard: the failure showed up only as redeems
    quietly reverting with `Slippage()`.
    """
    last = _load(path)["frames"][-1]
    fails = last.get("dmExitFails")
    if fails is None:
        pytest.skip("vector predates dmExitFails")
    assert fails == 0, (
        f"{fails} redemptions failed -- check the basket's slippage and "
        "conversion-loss guards against how hard the agents move the pools")


@pytest.mark.parametrize("path", _vectors())
def test_buck_k_stays_in_its_clamp(path):
    fr = _load(path)["frames"]
    ks = [f["buckK"] / E18 for f in fr]
    assert min(ks) >= 0.0, f"buckK below its floor: {min(ks):.4f}"
    assert max(ks) <= BUCK_K_MAX, f"buckK above its clamp: {max(ks):.4f}"
    assert all(f["basketVal"] > 0 for f in fr), "basket value must be positive"


@pytest.mark.parametrize("path", _vectors())
def test_pool_weights_track_the_mandate(path):
    """Actual value weights stay well inside the leash, and sum to one.

    The basket exists to hold a declared composition.  Buy-and-hold abandons
    that -- its mean absolute deviation runs to 49% over the same window --
    so bounded weights are the property that distinguishes a rebalanced
    basket from a drifting one.
    """
    fr = _load(path)["frames"]
    if not any("poolWeights" in f for f in fr):
        pytest.skip("vector predates poolWeights")
    worst, worst_day = 0.0, None
    for f in fr:
        for actual, target in f.get("poolWeights", []):
            dev = abs(actual - target)
            if dev > worst:
                worst, worst_day = dev, f["day"]
        aw = sum(w[0] for w in f.get("poolWeights", []))
        assert abs(aw - 1.0) < 1e-6, (
            f"day {f['day']}: actual weights sum to {aw}, not 1")
    assert worst < LEASH, (
        f"weight deviation {worst:.4f} on day {worst_day} reached the "
        f"{LEASH:.0%} leash -- the basket is no longer holding its mandate")


@pytest.mark.parametrize("path", _vectors())
def test_arbs_keep_the_pools_tracking_the_market(path):
    """The claim this whole scenario exists to demonstrate.

    BUCK-unaware arbitrageurs route through TOKEN/BUCK pools chasing
    cross-pool cycles.  As a side effect they hold those pools near the market
    reference -- both directly (TOKEN/USDC) and indirectly (TOKEN/BUCK priced
    through BUCK/USDC).  If routing breaks, these diverge without bound.
    """
    d = _load(path)
    fr = d["frames"]
    last = fr[-1]
    if "refUsd" not in last or not last.get("buckUsd"):
        pytest.skip("vector predates the price columns")
    names = d["tokens"]
    for i, sym in enumerate(names):
        ref = last["refUsd"][i]
        if not ref:
            continue
        direct = last["spotUsdc"][i]
        indirect = last["spotBuck"][i] * last["buckUsd"] / E6
        assert abs(direct - ref) / ref < MAX_TRACKING_ERR, (
            f"{sym}: TOKEN/USDC pool {direct / E6:,.4f} vs reference "
            f"{ref / E6:,.4f} -- direct arbitrage is not closing")
        assert abs(indirect - ref) / ref < MAX_TRACKING_ERR, (
            f"{sym}: TOKEN/BUCK routed to USD {indirect / E6:,.4f} vs "
            f"reference {ref / E6:,.4f} -- BUCK-routed arbitrage is not "
            "closing")


@pytest.mark.parametrize("path", _vectors())
def test_demand_leg_actually_trades(path):
    """A price-triggered agent that never fires is indistinguishable from a
    broken one, and the plot draws the same empty line either way."""
    d = _load(path)
    fr = d["frames"]
    last = fr[-1]
    # `dbb_bought` is snapshotted unconditionally and reads 0 both when the
    # agent is absent from the roster and when it is present but broken.
    # `arb2` carries per-agent inventory, so its rows exist if and only if the
    # agents do -- that is the discriminator, and without it this assertion
    # would fire on every scenario that simply does not run a demand leg.
    if not any(r.get("cls") == "dbb" for r in last.get("arb2", [])):
        pytest.skip("no basketeer agents in this scenario's roster")
    if len(fr) < 90:
        pytest.skip("run too short to expect a price trigger to fire")
    assert last["dbb_bought"] > 0, (
        "the basketeer demand leg bought no BUCK in the whole run -- check "
        "its hurdle against the basketValueInBuck the vector actually shows")
    assert last["dbb_parked"] > 0, (
        "the basketeer bought BUCK but parked none of it in the basket")
    assert last["dbb_bought"] >= last["dbb_parked"], (
        "parked more BUCK than it ever bought")
