"""Golden-vector conformance, Python side: every row of
test/vectors/math-vectors.json (generated by test/MathVectors.t.sol from
the REAL contract code paths) must reproduce bit-identically through the
buck_math kernel binding.  The Rust and JS suites assert the same file.

Build the binding first:  make nix-core-build-py
"""

import json
from pathlib import Path

import pytest

buck_math = pytest.importorskip(
    "buck_core.buck_math",
    reason="kernel binding not built (make nix-core-build-py)")

VECTORS = (Path(__file__).resolve().parents[3]
           / "test" / "vectors" / "math-vectors.json")


def rows():
    return json.loads(VECTORS.read_text())


def test_constants_match_the_contracts():
    assert buck_math.SECONDS_PER_YEAR == 365 * 86_400 + 6 * 3_600
    assert buck_math.BASE_RATE_PER_SEC == (2 * 10**25) // buck_math.SECONDS_PER_YEAR
    assert buck_math.MAX_BS == (1 << 120) - 1


def test_depreciation_vectors():
    n = 0
    for r in rows():
        if r["s"] != "dep":
            continue
        got = buck_math.depreciate(
            int(r["face"]), int(r["dep_type"]), int(r["rate_bp"]),
            int(r["floor"]), 0, int(r["elapsed"]))
        assert got == int(r["value"]), r
        n += 1
    assert n >= 250


def test_fee_vectors():
    n = 0
    for r in rows():
        if r["s"] != "fee":
            continue
        got = buck_math.fee_owing(
            int(r["buck_seconds"]), int(r["raw"]), int(r["elapsed"]))
        assert got == int(r["fee"]), r
        n += 1
    assert n >= 60


def test_carrying_vectors():
    n = 0
    for r in rows():
        if r["s"] != "carry":
            continue
        carried, from_raw, from_bs, to_raw, to_bs = buck_math.carrying_transfer(
            int(r["from_raw"]), int(r["from_bs"]), int(r["from_elapsed"]),
            int(r["to_raw"]), int(r["to_bs"]), int(r["to_elapsed"]),
            int(r["value"]))
        assert from_raw == int(r["from_raw_after"]), r
        assert from_bs == int(r["from_bs_after"]), r
        assert to_raw == int(r["to_raw_after"]), r
        assert to_bs == int(r["to_bs_after"]), r
        n += 1
    assert n >= 8


def test_funding_factor_vectors():
    n = 0
    pid = buck_math.DirectPid(0, 1, 0, 600, 0, 10**18, 5 * 10**17, 0)
    for r in rows():
        if r["s"] != "ff":
            continue
        pid.last_basket_cost = int(r["basket"])
        pid.last_buck_price = int(r["buck"])
        assert pid.funding_factor() == int(r["factor"]), r
        n += 1
    assert n >= 10


def test_pid_vectors():
    pid = None
    n = 0
    for r in rows():
        if r["s"] == "pid_params":
            pid = buck_math.DirectPid(
                int(r["kp"]), int(r["ki"]), int(r["kd"]), int(r["dt"]),
                int(r["kmin"]), int(r["kmax"]), int(r["k0"]), int(r["t0"]))
            pid.dt_max = int(r["dt_max"])
        elif r["s"] == "pid":
            k = pid.compute(int(r["t"]), int(r["basket"]))
            assert k == int(r["buck_k"]), r
            assert pid.p == int(r["p"]), r
            assert pid.i == int(r["i"]), r
            assert pid.d == int(r["d"]), r
            assert pid.last_update == int(r["last_update"]), r
            assert pid.funding_factor() == int(r["ff"]), r
            n += 1
    assert n == 12
