//! Golden-vector conformance: every row of test/vectors/math-vectors.json
//! (generated by test/MathVectors.t.sol from the REAL contract code paths)
//! must reproduce bit-identically.  The Python and JS suites assert the
//! same file through the kernel bindings.

use serde_json::Value;

use buck_math::{
    carrying_transfer, depreciate, fee_owing, DepType, DirectPid,
};

fn u(v: &Value, k: &str) -> u128 {
    v[k].as_str().unwrap().parse().unwrap()
}

fn i(v: &Value, k: &str) -> i128 {
    v[k].as_str().unwrap().parse().unwrap()
}

fn load() -> Vec<Value> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"),
                       "/tests/vectors/math-vectors.json");
    let text = std::fs::read_to_string(path)
        .expect("run `make nix-match-MathVectors` to generate the vectors");
    serde_json::from_str(&text).unwrap()
}

#[test]
fn golden_vectors() {
    let rows = load();
    let mut counts = std::collections::HashMap::new();
    let mut pid: Option<DirectPid> = None;

    for row in &rows {
        let s = row["s"].as_str().unwrap();
        *counts.entry(s.to_string()).or_insert(0u32) += 1;
        match s {
            "dep" => {
                let got = depreciate(
                    u(row, "face"),
                    DepType::from_u8(u(row, "dep_type") as u8),
                    u(row, "rate_bp") as u32,
                    u(row, "floor"),
                    0,
                    u(row, "elapsed") as u64,
                );
                assert_eq!(got, u(row, "value"), "dep row {row}");
            }
            "fee" => {
                let got = fee_owing(
                    u(row, "buck_seconds"),
                    i(row, "raw"),
                    u(row, "elapsed") as u64,
                );
                assert_eq!(got, u(row, "fee"), "fee row {row}");
            }
            "carry" => {
                let r = carrying_transfer(
                    i(row, "from_raw"), u(row, "from_bs"),
                    u(row, "from_elapsed") as u64,
                    i(row, "to_raw"), u(row, "to_bs"),
                    u(row, "to_elapsed") as u64,
                    u(row, "value"),
                );
                assert_eq!(r.from_raw, i(row, "from_raw_after"), "carry {row}");
                assert_eq!(r.from_bs, u(row, "from_bs_after"), "carry {row}");
                assert_eq!(r.to_raw, i(row, "to_raw_after"), "carry {row}");
                assert_eq!(r.to_bs, u(row, "to_bs_after"), "carry {row}");
            }
            "ff" => {
                // A throwaway controller carrying the row's references.
                let mut c = DirectPid::new(0, 1, 0, 600, 0,
                                           1_000_000_000_000_000_000,
                                           500_000_000_000_000_000, 0);
                c.last_basket_cost = i(row, "basket");
                c.last_buck_price = i(row, "buck");
                assert_eq!(c.funding_factor(), u(row, "factor"), "ff {row}");
            }
            "pid_params" => {
                pid = Some(DirectPid::new(
                    i(row, "kp"), i(row, "ki"), i(row, "kd"),
                    u(row, "dt") as u64,
                    u(row, "kmin"), u(row, "kmax"), u(row, "k0"),
                    u(row, "t0") as u64,
                ));
                pid.as_mut().unwrap().dt_max = u(row, "dt_max") as u64;
            }
            "pid" => {
                let c = pid.as_mut().expect("pid_params precedes pid rows");
                let k = c.compute(u(row, "t") as u64, i(row, "basket"));
                assert_eq!(k, u(row, "buck_k"), "pid K {row}");
                assert_eq!(c.p, i(row, "p"), "pid P {row}");
                assert_eq!(c.i, i(row, "i"), "pid I {row}");
                assert_eq!(c.d, i(row, "d"), "pid D {row}");
                assert_eq!(c.last_update as u128, u(row, "last_update"),
                           "pid lastUpdate {row}");
                assert_eq!(c.funding_factor(), u(row, "ff"), "pid ff {row}");
            }
            other => panic!("unknown vector section {other}"),
        }
    }

    // The generator's shape: refuse to pass on a truncated file.
    assert!(counts["dep"] >= 250, "dep rows: {:?}", counts);
    assert!(counts["fee"] >= 60, "fee rows: {:?}", counts);
    assert!(counts["carry"] >= 8, "carry rows: {:?}", counts);
    assert!(counts["ff"] >= 10, "ff rows: {:?}", counts);
    assert_eq!(counts["pid"], 12, "pid rows: {:?}", counts);
}
